### ISSUE TITLE
Is the travis bot working correctly?

### ISSUE THREAD

**Issue by darren-west** [travis-ci/apt-package-whitelist#3495]
The packages I have requested seem to have been tested 3 times by the travis bot with no errors an no pull requests. 

I have had a look back and it looks like none of the requests have been completed in the last week or so?

**Comment by BanzaiMan** [comment]
Sorry about the delay. I'm working on it.

**Comment by iphydf** [comment]
(Cross-posted from some package bug I now lost track of)

Every package fails, because the name "Raphael Pinson" is decoded incorrectly: https://travis-ci.org/travis-ci/apt-whitelist-checker/builds/174487752#L343

```
Adding {"alias"=>"augeas", "sourceline"=>"ppa:raphink/augeas", "key_url"=>nil}
gpg: keyring `/tmp/tmp7kaj2kfz/secring.gpg' created
gpg: keyring `/tmp/tmp7kaj2kfz/pubring.gpg' created
gpg: requesting key AE498453 from hkp server keyserver.ubuntu.com
gpg: /tmp/tmp7kaj2kfz/trustdb.gpg: trustdb created
gpg: key AE498453: public key "Launchpad PPA for Rapha�l Pinson" imported
gpg: Total number processed: 1
gpg:               imported: 1  (RSA: 1)
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.4/threading.py", line 920, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.4/threading.py", line 868, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3/dist-packages/softwareproperties/SoftwareProperties.py", line 687, in addkey_func
    func(**kwargs)
  File "/usr/lib/python3/dist-packages/softwareproperties/ppa.py", line 370, in add_key
    return apsk.add_ppa_signing_key()
  File "/usr/lib/python3/dist-packages/softwareproperties/ppa.py", line 261, in add_ppa_signing_key
    tmp_export_keyring, signing_key_fingerprint, tmp_keyring_dir):
  File "/usr/lib/python3/dist-packages/softwareproperties/ppa.py", line 210, in _verify_fingerprint
    got_fingerprints = self._get_fingerprints(keyring, keyring_dir)
  File "/usr/lib/python3/dist-packages/softwareproperties/ppa.py", line 202, in _get_fingerprints
    output = subprocess.check_output(cmd, universal_newlines=True)
  File "/usr/lib/python3.4/subprocess.py", line 609, in check_output
    output, unused_err = process.communicate(inputdata, timeout=timeout)
  File "/usr/lib/python3.4/subprocess.py", line 947, in communicate
    stdout = _eintr_retry_call(self.stdout.read)
  File "/usr/lib/python3.4/subprocess.py", line 491, in _eintr_retry_call
    return func(*args)
  File "/usr/lib/python3.4/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 94: ordinal not in range(128)
```

**Comment by BanzaiMan** [comment]
I don't think so. Adding the relevant key fails, but the rest of the steps should be working.
